BF: remove empty "required" fields -- causes jsonschema to barf
$> jsonschema -i ds000001_model.json schema.json
Traceback (most recent call last):
  File "/usr/bin/jsonschema", line 11, in <module>
    load_entry_point(jsonschema==2.6.0, console_scripts, jsonschema)()
  File "/usr/lib/python2.7/dist-packages/jsonschema/cli.py", line 67, in main
    sys.exit(run(arguments=parse_args(args=args)))
  File "/usr/lib/python2.7/dist-packages/jsonschema/cli.py", line 74, in run
    validator.check_schema(arguments["schema"])
  File "/usr/lib/python2.7/dist-packages/jsonschema/validators.py", line 83, in check_schema
    raise SchemaError.create_from(error)
jsonschema.exceptions.SchemaError: [] is too short

Failed validating uminItems in schema[uproperties][uproperties][uadditionalProperties][uproperties][urequired]:
    {uitems: {utype: ustring},
     uminItems: 1,
     utype: uarray,
     uuniqueItems: True}

On instance[uproperties][uinput][urequired]:
    []